### ISSUE TITLE
No known conditions for "./lib/locale/lang/zh-cn" entry in "element-plus"

### ISSUE THREAD

**Issue by marklove5102** [zzzzbw/Fame#52]
`````
@:~/1.垃圾/Fame$ docker-compose up
Building fame-admin
DEPRECATED: The legacy builder is deprecated and will be removed in a future release.
            Install the buildx component to build images with BuildKit:
            https://docs.docker.com/go/buildx/

Sending build context to Docker daemon  6.406MB
Step 1/13 : FROM node:16-alpine as build-stage
 ---> 2573171e0124
Step 2/13 : RUN npm config set registry https://registry.npm.taobao.org
 ---> Using cache
 ---> 1a1151e9a40a
Step 3/13 : WORKDIR /app
 ---> Using cache
 ---> 7d93c16b69cb
Step 4/13 : COPY ./fame-admin/package*.json ./
 ---> Using cache
 ---> bd438274a6f4
Step 5/13 : RUN npm install
 ---> Using cache
 ---> a8d0b73155c0
Step 6/13 : COPY ./fame-admin .
 ---> Using cache
 ---> 080d581c670b
Step 7/13 : RUN npm run build
 ---> Running in 41437b4ad22d

> element-plus-vite-starter@0.1.0 build
> vite build

{
  VITE_BASE_PATH: '/admin/',
  VITE_APP_BASE_SERVER_URL: '/',
  VITE_APP_BASE_FRONT_URL: '/'
}
vite v2.9.16 building for production...
transforming...
✓ 27 modules transformed.
[vite:resolve] No known conditions for "./lib/locale/lang/zh-cn" entry in "element-plus" package
error during build:
Error: No known conditions for "./lib/locale/lang/zh-cn" entry in "element-plus" package
    at bail (/app/node_modules/vite/dist/node/chunks/dep-6e2fe41e.js:38597:8)
    at resolve (/app/node_modules/vite/dist/node/chunks/dep-6e2fe41e.js:38669:9)
    at resolveExports (/app/node_modules/vite/dist/node/chunks/dep-6e2fe41e.js:40982:12)
    at resolveDeepImport (/app/node_modules/vite/dist/node/chunks/dep-6e2fe41e.js:41000:31)
    at tryNodeResolve (/app/node_modules/vite/dist/node/chunks/dep-6e2fe41e.js:40773:20)
    at Object.resolveId (/app/node_modules/vite/dist/node/chunks/dep-6e2fe41e.js:40581:28)
    at /app/node_modules/rollup/dist/shared/rollup.js:22826:37
The command '/bin/sh -c npm run build' returned a non-zero code: 1
ERROR: Service 'fame-admin' failed to build : Build failed

`````

**Comment by bihell** [comment]
这目录名666

**Comment by marklove5102** [comment]
> 这目录名666

在跑起来之前都在这目录，防止时间长忘记有垃圾存在硬盘
