### ISSUE TITLE
回复用户评论邮件发送出错,而且自己不应收到回复给用户的邮件

### ISSUE THREAD

**Issue by bihell** [zzzzbw/Fame#9]
当你在文章页面回复用户的时候，此时系统发送邮件给用户会出错，此外博主回复给用户，应该不需要再发邮件给博主

错误信息如下

fame-server    | 2019-05-18 10:38:48.001 ERROR 1 --- [         task-3] org.thymeleaf.TemplateEngine             : [THYMELEAF][task-3] Exception processing template "mail_user": Error resolving template [mail_user], template might not exist or might not be accessible by any of the configured Template Resolvers
fame-server    |
fame-server    | org.thymeleaf.exceptions.TemplateInputException: Error resolving template [mail_user], template might not exist or might not be accessible by any of the configured Template Resolvers
fame-server    | 	at org.thymeleaf.engine.TemplateManager.resolveTemplate(TemplateManager.java:869) ~[thymeleaf-3.0.11.RELEASE.jar:3.0.11.RELEASE]
fame-server    | 	at org.thymeleaf.engine.TemplateManager.parseAndProcess(TemplateManager.java:607) ~[thymeleaf-3.0.11.RELEASE.jar:3.0.11.RELEASE]
fame-server    | 	at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1098) [thymeleaf-3.0.11.RELEASE.jar:3.0.11.RELEASE]
fame-server    | 	at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1059) [thymeleaf-3.0.11.RELEASE.jar:3.0.11.RELEASE]
fame-server    | 	at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1048) [thymeleaf-3.0.11.RELEASE.jar:3.0.11.RELEASE]
fame-server    | 	at com.zbw.fame.service.impl.EmailServiceImpl.sendEmailToUser(EmailServiceImpl.java:80) [classes/:na]
fame-server    | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_181]
fame-server    | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_181]
fame-server    | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_181]
fame-server    | 	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_181]
fame-server    | 	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343) [spring-aop-5.1.2.RELEASE.jar:5.1.2.RELEASE]
fame-server    | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198) [spring-aop-5.1.2.RELEASE.jar:5.1.2.RELEASE]
fame-server    | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) [spring-aop-5.1.2.RELEASE.jar:5.1.2.RELEASE]
fame-server    | 	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:294) ~[spring-tx-5.1.2.RELEASE.jar:5.1.2.RELEASE]
fame-server    | 	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98) ~[spring-tx-5.1.2.RELEASE.jar:5.1.2.RELEASE]
fame-server    | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) [spring-aop-5.1.2.RELEASE.jar:5.1.2.RELEASE]
fame-server    | 	at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115) ~[spring-aop-5.1.2.RELEASE.jar:5.1.2.RELEASE]
fame-server    | 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_181]
fame-server    | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_181]
fame-server    | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_181]
fame-server    | 	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_181]
fame-server    |
fame-server    | 2019-05-18 10:38:48.012 ERROR 1 --- [         task-3] .a.i.SimpleAsyncUncaughtExceptionHandler : Unexpected exception occurred invoking async method: public void com.zbw.fame.service.impl.EmailServiceImpl.sendEmailToUser(com.zbw.fame.model.domain.Comment,java.lang.String)
fame-server    |
fame-server    | org.thymeleaf.exceptions.TemplateInputException: Error resolving template [mail_user], template might not exist or might not be accessible by any of the configured Template Resolvers
fame-server    | 	at org.thymeleaf.engine.TemplateManager.resolveTemplate(TemplateManager.java:869) ~[thymeleaf-3.0.11.RELEASE.jar:3.0.11.RELEASE]
fame-server    | 	at org.thymeleaf.engine.TemplateManager.parseAndProcess(TemplateManager.java:607) ~[thymeleaf-3.0.11.RELEASE.jar:3.0.11.RELEASE]
fame-server    | 	at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1098) ~[thymeleaf-3.0.11.RELEASE.jar:3.0.11.RELEASE]
fame-server    | 	at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1059) ~[thymeleaf-3.0.11.RELEASE.jar:3.0.11.RELEASE]
fame-server    | 	at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1048) ~[thymeleaf-3.0.11.RELEASE.jar:3.0.11.RELEASE]
fame-server    | 	at com.zbw.fame.service.impl.EmailServiceImpl.sendEmailToUser(EmailServiceImpl.java:80) ~[classes/:na]
fame-server    | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_181]
fame-server    | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_181]
fame-server    | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_181]
fame-server    | 	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_181]
fame-server    | 	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343) ~[spring-aop-5.1.2.RELEASE.jar:5.1.2.RELEASE]
fame-server    | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198) ~[spring-aop-5.1.2.RELEASE.jar:5.1.2.RELEASE]
fame-server    | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.1.2.RELEASE.jar:5.1.2.RELEASE]
fame-server    | 	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:294) ~[spring-tx-5.1.2.RELEASE.jar:5.1.2.RELEASE]
fame-server    | 	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98) ~[spring-tx-5.1.2.RELEASE.jar:5.1.2.RELEASE]
fame-server    | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.1.2.RELEASE.jar:5.1.2.RELEASE]
fame-server    | 	at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115) ~[spring-aop-5.1.2.RELEASE.jar:5.1.2.RELEASE]
fame-server    | 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_181]
fame-server    | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_181]
fame-server    | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_181]
fame-server    | 	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_181]
fame-server    |

**Comment by bihell** [comment]
4b9428836e34325204f59709e3c3ae98ed42b341 已处理
